<a href="https://colab.research.google.com/github/chineduemmanuel/alx-pre_course/blob/main/Data_Science_Lifecycle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## How to use Colaboratory notebook

This notebook includes an example of using `numpy` library to create a $3\times4$ matrix filled with random numbers between 1 and 10.

In [2]:
import numpy as np

# Create an array of random numbers
random_nums = np.random.randint(low=5, high=15, size=(4, 4))
print("Random Numbers:")
print(random_nums)

Random Numbers:
[[13  8 12 13]
 [10  9 12 14]
 [ 5 11  9 14]
 [14 12  6 10]]


In [3]:
# Calculate the sum, minimum, and maximum of the array
print("\nSum:", np.sum(random_nums))
print("Minimum:", np.min(random_nums))
print("Maximum:", np.max(random_nums))


Sum: 172
Minimum: 5
Maximum: 14
